### ISSUE TITLE
Crash with Blabber

### ISSUE THREAD

**Issue by Pyrofab** [GravityCY/EasyRename#2]
[Blabber](https://modrinth.com/mod/blabber) adds a `HandledScreen` with no slots, which seems to conflict with the assumption made [here](https://github.com/GravityCY/EasyRename/blob/master/src/main/java/me/gravityio/easyrename/mixins/impl/ServerPlayerEntityMixin.java#L34) that every `HandledScreen` has a backing inventory.

[message.txt](https://github.com/user-attachments/files/15846136/message.txt)

**Comment by GravityCY** [comment]
Right, let me see if it's as simple of a fix as I think

**Comment by Pyrofab** [comment]
By the way, I believe this `@Redirect` could be replaced with a `@WrapOperation` to limit mixin incompatibilities with other mods

**Comment by GravityCY** [comment]
In 1.20.5 I made it an inject and create my own packet rather than modifying the vanilla packet, but I don't really want to backport that for older versions (I probably should, I just want to move forward with the mc versions)

**Comment by GravityCY** [comment]
Published the fix for 1.20 - 1.21, could you please confirm that it's resolved?
https://modrinth.com/mod/easyrename/version/0.3.4+1.20

**Comment by Metaloul** [comment]
Hey Gravity ! I'm the guy who reported the bug to Pyro's discord mod. It seem to be fixed :D
Thanks a lot for you quick fix dude. Really appreciate it ! <3

**Comment by GravityCY** [comment]
No worries, thanks for letting me know about the bug! :D
