### ISSUE TITLE
Incompatible with Essential Mod

### ISSUE THREAD

**Issue by codyiscod** [GravityCY/EasyRename#3]
When adding this mod to a modpack, Essential no longer starts.
The mod can be found on these websites:

[https://essential.gg/en](https://essential.gg/en)
[https://www.curseforge.com/minecraft/mc-mods/essential-mod](https://www.curseforge.com/minecraft/mc-mods/essential-mod)
[https://modrinth.com/mod/essential](https://modrinth.com/mod/essential)

I couldn't find anything useful in the logs because I have such a big modpack, but I am almost certain this is what was causing it not to work.

Please fix this if u can :)

**Comment by codyiscod** [comment]
If you'd like to test the mod list/modpack I am using, it is available on Modrinth: [Lightly Modded b2.2-1](https://modrinth.com/modpack/lightlymodded/version/b2.2-1)

**Comment by GravityCY** [comment]
Will look into it, thanks for the report.

**Comment by GravityCY** [comment]
Hey, it was a pretty simple fix, can you confirm that it's all good for you? (Only for 1.21 though)

**Comment by codyiscod** [comment]
As far as I can tell, it seems to be working now, thanks!

**Comment by GravityCY** [comment]
👍
